### ISSUE TITLE
Issue with adding firewall rules

### ISSUE THREAD

**Issue by omawnakw** [hetznercloud/cli#302]
New firewall code to add rules actually does not work returning the error below.
The issue is that slice was defined with zero length. Either need to define slice with len(sourceIPs) like this: `rule.SourceIPs = make([]net.IPNet, len(sourceIPs))`
or to leave it zero-length and len(sourceIPs) capacity and use append() to add elements.

`
 ~/go/bin/hcloud firewall add-rule test-firewall --protocol tcp --direction in --port 80 --source-ips 8.8.8.8/24 --source-ips 77.88.8.8/32
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/hetznercloud/cli/internal/cmd/firewall.runAddRule(0xc00012a750, 0xc0001c8b00, 0xc0000e0e70, 0x1, 0xb, 0x0, 0x0)
	/Users/omawnakw/go/src/github.com/hetznercloud/cli/internal/cmd/firewall/add_rule.go:93 +0xe6c
github.com/hetznercloud/cli/internal/state.(*State).Wrap.func1(0xc0001c8b00, 0xc0000e0e70, 0x1, 0xb, 0x0, 0x0)
	/Users/omawnakw/go/src/github.com/hetznercloud/cli/internal/state/helpers.go:26 +0x56
github.com/spf13/cobra.(*Command).execute(0xc0001c8b00, 0xc0000be030, 0xb, 0xb, 0xc0001c8b00, 0xc0000be030)
	/Users/omawnakw/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000acb00, 0xc0000acb00, 0x0, 0xc00012a820)
	/Users/omawnakw/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/omawnakw/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/Users/omawnakw/go/src/github.com/hetznercloud/cli/cmd/hcloud/main.go:37 +0x73
`

**Comment by LKaemmerling** [comment]
Hey @omawnakw,

we released v1.21.1 which should fix your issue:
https://github.com/hetznercloud/cli/releases/tag/v1.21.1
