### ISSUE TITLE
SIGSEGV on server list

### ISSUE THREAD

**Issue by my-git-hub** [hetznercloud/cli#463]
Hi!

I've installed hcloud-cli on Ubuntu 22.04
```
root@localhost:~$  sudo apt-get install hcloud-cli
hcloud-cli is already the newest version (1.13.0-2build2).
```

There's a SIGSEGV error when running `server list`
```
root@localhost:~$ hcloud server list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e55a6]

goroutine 1 [running]:
net.networkNumberAndMask(0x0, 0x4, 0xc00002e180, 0x48327c, 0xc00004c800, 0x0, 0x0)
        net/ip.go:476 +0x26
net.(*IPNet).String(0x0, 0xc0003bc230, 0xc0000a6270)
        net/ip.go:526 +0x45
github.com/hetznercloud/cli/cli.describeServerListTableOutput.func2(0x871280, 0xc00017f340, 0x91fb5b, 0x4)
        github.com/hetznercloud/cli/cli/server_list.go:79 +0x45
github.com/hetznercloud/cli/cli.(*tableOutput).Write(0xc000616840, 0xc000101c88, 0x6, 0x6, 0x871280, 0xc00017f340)
        github.com/hetznercloud/cli/cli/output.go:265 +0x2e5
github.com/hetznercloud/cli/cli.runServerList(0xc0000fdc70, 0xc00012eb00, 0xc5b0f8, 0x0, 0x0, 0x0, 0x0)
        github.com/hetznercloud/cli/cli/server_list.go:64 +0x3ea
github.com/hetznercloud/cli/cli.(*CLI).wrap.func1(0xc00012eb00, 0xc5b0f8, 0x0, 0x0, 0x0, 0x0)
        github.com/hetznercloud/cli/cli/cli.go:118 +0x56
github.com/spf13/cobra.(*Command).execute(0xc00012eb00, 0xc0000a2170, 0x0, 0x0, 0xc00012eb00, 0xc0000a2170)
        github.com/spf13/cobra/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e0580, 0x0, 0x0, 0xc000157520)
        github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra/command.go:895
main.main()
        github.com/hetznercloud/cli/cmd/hcloud/main.go:35 +0x65
```
        
If output is limited to just a few columns, it works.

There's around 150 servers in a group.

**Comment by apricote** [comment]
Hey @my-git-hub,

it looks like you are using a really old and outdated version of the cli (`v1.13.0`, 3.5 years old), the latest release is `v1.31.1`, please try to use a newer version instead. You can read about the supported installation methods in our [README](https://github.com/hetznercloud/cli/tree/v1.13.0#installation).

If you have any further questions, please feel free to ask them in this issue.
