### ISSUE TITLE
hcloud server list - panic: runtime error: invalid memory address or nil pointer dereference - on Ubuntu 22.04

### ISSUE THREAD

**Issue by madsoliver** [hetznercloud/cli#541]
Hi,
I am able to create a server, but not list my servers.
When running the command vis ssh on a hetzner cloud instance i get the following error:
```
root@controller-helsinki:~# hcloud server list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ae5c0]

goroutine 1 [running]:
net.networkNumberAndMask(0x0, 0x40, 0xffffa63c0108, 0x40000648c0, 0x40005558b8, 0x384460, 0x0)
        net/ip.go:476 +0x20
net.(*IPNet).String(0x0, 0x4000310170, 0xf)
        net/ip.go:526 +0x28
github.com/hetznercloud/cli/cli.describeServerListTableOutput.func2(0x3da280, 0x40001d7a20, 0x488af5, 0x4)
        github.com/hetznercloud/cli/cli/server_list.go:79 +0x40
github.com/hetznercloud/cli/cli.(*tableOutput).Write(0x4000517a70, 0x4000555c58, 0x6, 0x6, 0x3da280, 0x40001d7a20)
        github.com/hetznercloud/cli/cli/output.go:265 +0x234
github.com/hetznercloud/cli/cli.runServerList(0x400007e0e0, 0x40001a0580, 0x7c6fe0, 0x0, 0x0, 0x400010fcc8, 0x0)
        github.com/hetznercloud/cli/cli/server_list.go:64 +0x2bc
github.com/hetznercloud/cli/cli.(*CLI).wrap.func1(0x40001a0580, 0x7c6fe0, 0x0, 0x0, 0x0, 0x0)
        github.com/hetznercloud/cli/cli/cli.go:118 +0x50
github.com/spf13/cobra.(*Command).execute(0x40001a0580, 0x4000096170, 0x0, 0x0, 0x40001a0580, 0x4000096170)
        github.com/spf13/cobra/command.go:850 +0x30c
github.com/spf13/cobra.(*Command).ExecuteC(0x4000188000, 0x0, 0x0, 0x40001e2000)
        github.com/spf13/cobra/command.go:958 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra/command.go:895
main.main()
        github.com/hetznercloud/cli/cmd/hcloud/main.go:35 +0x4c
root@controller-helsinki:~#
```

Running the same command on my local machine (also Ubuntu 22.04), it does not produce the error.

What can be the problem here?

**Comment by apricote** [comment]
Hey @madsoliver, this sounds like an old bug that should be solved already. What version of hcloud are you running (`hcloud version`) and does this still happen on the latest version (v1.37.0 right now)?

**Comment by madsoliver** [comment]
running hcloud version gave me "was not built properly".
After reinstalling it worked out 🙂

Thanks for pointing me in the right direction!
