### ISSUE TITLE
failing dhcp during cloud-init

### ISSUE THREAD

**Issue by MartinNowak** [hetznercloud/cli#597]
Hope this is a reasonable place to file this issue.

While recreating our 32 hcloud servers, we occasionally have a sizable amount of servers that get stuck in cloud-init.
I debugged this a bit in the rescue console today and it seems to be caused by a race condition between the network interface and dhcp. All those servers only have a private network attached.

```
2023-11-01 05:43:29,248 - dhcp.py[DEBUG]: Skip dhcp_discovery: Unable to find fallback nic.
...
2023-11-01 05:43:29,249 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceHetzner.DataSourceHetzner'> failed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/cloudinit/sources/__init__.py", line 924, in find_source
    if s.update_metadata_if_supported(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/sources/__init__.py", line 806, in update_metadata_if_supported
    result = self.get_data()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/sources/__init__.py", line 365, in get_data
    return_value = self._get_data()
                   ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/sources/DataSourceHetzner.py", line 58, in _get_data
    with EphemeralDHCPv4(
  File "/usr/lib/python3.11/site-packages/cloudinit/net/dhcp.py", line 75, in __enter__
    return self.obtain_lease()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/net/dhcp.py", line 100, in obtain_lease
    leases = maybe_perform_dhcp_discovery(self.iface, self.dhcp_log_func)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/net/dhcp.py", line 173, in maybe_perform_dhcp_discovery
    raise NoDHCPLeaseInterfaceError()
cloudinit.net.dhcp.NoDHCPLeaseInterfaceError
```

# Context
https://github.com/canonical/cloud-init/blob/d78ff3780091c91808c1d53de4cc96fcfdd4e43e/cloudinit/net/dhcp.py#L121

**Comment by jooola** [comment]
Hey @MartinNowak 

I recommend you to open a ticket on https://console.hetzner.cloud/support instead of here, so you get the best answer from the team responsible for your issue.

I am going to close as it is not related to the CLI.
